### ISSUE TITLE
iOS application crashed on launch

### ISSUE THREAD

**Issue by nikesh8** [flowkey/react-native-home-indicator#31]
I have the latest version installed of this package but unfortunately, my application crashed on launch.
Please help me out of this situation. Following is my error message which I am getting from xCode.

> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'rootViewController is not of type HomeIndicatorViewController as expected.'

Can anyone help me out of this situation?
Thanks in advance.

**Comment by michaelknoch** [comment]
@nikesh8 did you follow [the steps in the getting started section](https://github.com/flowkey/react-native-home-indicator#getting-started) of the readme? Your rootviewController has to be initialised like this: `UIViewController *rootViewController = [HomeIndicatorViewController new];`

**Comment by nikesh8** [comment]
> @nikesh8 did you follow [the steps in the getting started section](https://github.com/flowkey/react-native-home-indicator#getting-started) of the readme? Your rootviewController has to be initialised like this: `UIViewController *rootViewController = [HomeIndicatorViewController new];`

@michaelknoch Yes I have added this line on my `Appdelegate.m` as mentioned in Getting Started.

FYI, I am on following `react` and `react-native` version

```
"react": "16.13.1",
"react-native": "0.63.2"
```

**Comment by michaelknoch** [comment]
did you just "add" the line, or did you replace it with the original initialisation of `rootViewController`

can you search for `UIViewController *rootViewController = ` in your appdelegate? I am assuming that the rootViewController gets reinited with the original react native view controller after `UIViewController *rootViewController = [HomeIndicatorViewController new];` has happened @nikesh8

**Comment by ideopunk** [comment]
I'm facing what I think is the same issue. In my `AppDelegate.m` the line is `UIViewController *rootViewController = [self.reactDelegate createRootViewController];` instead of `... [UIViewController new];`. I replace it with `.... [HomeIndicatorViewController new]`. Upon launch I get the same error as @nikesh8. Should I be adding the line instead of replacing it?
