### ISSUE TITLE
Could not find a declaration file for module 'react-native-home-indicator'. '....../node_modules/react-native-home-indicator/index.js' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by IlanZ93** [flowkey/react-native-home-indicator#41]
Hey,

![136217281-678ea873-c082-4bc2-8091-bd50b8751d57](https://user-images.githubusercontent.com/23208231/136217697-d2958c76-79e5-4b0b-a715-84906e9d9f5f.png)

My project is using TypeScript so I have this issue and can't be solve, can you maybe publish new declaration or if you are aware of a new way to hide the Home indicator on React Native 0.64...

Thank you

**Comment by kikeztw** [comment]
> Hey,
> 
> ![136217281-678ea873-c082-4bc2-8091-bd50b8751d57](https://user-images.githubusercontent.com/23208231/136217697-d2958c76-79e5-4b0b-a715-84906e9d9f5f.png)
> 
> My project is using TypeScript so I have this issue and can't be solve, can you maybe publish new declaration or if you are aware of a new way to hide the Home indicator on React Native 0.64...
> 
> Thank you

just add to in root of you project

```ts
// index.d.ts
declare module 'react-native-home-indicator' {
  import React from 'react';

  type HomeIndicatorProps = {
    autoHidden?: boolean;
  };

  // eslint-disable-next-line import/no-default-export
  export default class HomeIndicator extends React.Component<HomeIndicatorProps> {
    popAndGetPreviousProps(): void;
  }
}

```

**Comment by michaelknoch** [comment]
I opened a PR which addresses the missing types. Basically I converted the module to TS and also refactored the react class to hooks. This needs some testing but it will presumably go live within the next days. @kikeztw @IlanZ93
