### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by kesha-antonov** [flowkey/react-native-home-indicator#52]
Hi!

I see home indicator on simulators iphone & ipad. Also on real device - ipad

I've tried both

`
<HomeIndicator autoHidden={isHomeIndicatorHidden} />
<PrefersHomeIndicatorAutoHidden />
`

Do you have any advice please?

<img width="429" alt="Screenshot 2023-06-07 at 15 05 56" src="https://github.com/flowkey/react-native-home-indicator/assets/11584712/1537579b-2e67-4702-9ba5-88d71999f870">

<img width="782" alt="Screenshot 2023-06-07 at 15 06 25" src="https://github.com/flowkey/react-native-home-indicator/assets/11584712/0776f211-62c5-4d72-85b5-36c117abad1d">

**Comment by michaelknoch** [comment]
Are you using react-navigation? Can you create a repo for reproduction? @kesha-antonov

**Comment by kesha-antonov** [comment]
> Are you using react-navigation? Can you create a repo for reproduction? @kesha-antonov 

Yes, but I don't use native-stack

I'll create the repo later today

**Comment by kesha-antonov** [comment]
@michaelknoch hi
Should I also hide status bar in order to hide home indicator?

**Comment by mehthabux** [comment]
Did someone found a solution for this ?
Its not working for me as well

**Comment by kesha-antonov** [comment]
Seems like issue was with react-navigtion

**Comment by michaelknoch** [comment]
@kesha-antonov did you manage to fix the behaviour by updating react navigation?

**Comment by kesha-antonov** [comment]
> @kesha-antonov did you manage to fix the behaviour by updating react navigation?

It was few months ago - I think I updated to native-stack and used `autoHideHomeIndicator` prop. https://reactnavigation.org/docs/native-stack-navigator/#autohidehomeindicator
